### ISSUE TITLE
 Additional errors if eiger_odin_fan_ready times out

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#294]
If the eiger fan ready times out we get the following error as well as the timeout:

```
[2024-01-16 11:22:32,284] ophyd status ERROR: SubscriptionStatus(device=eiger_odin_fan_ready, done=True, success=False) encountered an error during _handle_failure()
Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/hyperion_v8.5.0/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 260, in _run_callbacks
    self._handle_failure()
  File "/dls_sw/i03/software/bluesky/hyperion_v8.5.0/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 760, in _handle_failure
    return super()._handle_failure()
  File "/dls_sw/i03/software/bluesky/hyperion_v8.5.0/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 654, in _handle_failure
    self.device.stop()
AttributeError: 'EpicsSignalRO' object has no attribute 'stop'
```
This is because the `SubscriptionStatus`, that is subscribed to `ready` will try and stop the signal but the signal is RO.

This will need to be fixed in ophyd by either checking for whether the device is stoppable or adding a stop to the ROSignal that does nothing

**Comment by DominicOram** [comment]
Fixed by https://github.com/bluesky/ophyd/pull/1245
