### ISSUE TITLE
Errors on statuses not cleaned up after tests 

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/dodal#334]
Just a cosmetic problem really, but sometimes quite a lot of stuff printed after test completion, e.g.

```
--- Logging error ---
Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 236, in _run_callbacks
    self.log.warning("%r has timed out", self)
Message: '%r has timed out'
Arguments: (SubscriptionStatus(device=test fake Eiger_odin_meta_file_name, done=False, success=False),)
--- Logging error ---
Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 236, in _run_callbacks
    self.log.warning("%r has timed out", self)
Message: '%r has timed out'
Arguments: (SubscriptionStatus(device=test fake Eiger_odin_file_writer_id, done=False, success=False),)
--- Logging error ---
Traceback (most recent call last):
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 260, in _run_callbacks
    self._handle_failure()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 760, in _handle_failure
    return super()._handle_failure()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 654, in _handle_failure
    self.device.stop()
AttributeError: 'FakeEpicsSignalRO' object has no attribute 'stop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 262, in _run_callbacks
    self.log.exception(
Message: '%r encountered an error during _handle_failure()'
Arguments: (SubscriptionStatus(device=test fake Eiger_odin_meta_file_name, done=True, success=False),)
--- Logging error ---
Traceback (most recent call last):
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 260, in _run_callbacks
    self._handle_failure()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 760, in _handle_failure
    return super()._handle_failure()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 654, in _handle_failure
    self.device.stop()
AttributeError: 'FakeEpicsSignalRO' object has no attribute 'stop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/status.py", line 262, in _run_callbacks
    self.log.exception(
Message: '%r encountered an error during _handle_failure()'
Arguments: (SubscriptionStatus(device=test fake Eiger_odin_file_writer_id, done=True, success=False),)
--- Logging error ---
Traceback (most recent call last):
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_dispatch.py", line 55, in run
    callback(*args, **kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/signal.py", line 1147, in _pv_connected
    self._add_callback(pvname, pv, self._read_changed)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/signal.py", line 1207, in _add_callback
    mon = pv.add_callback(cb, run_now=pv.connected)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_pyepics_shim.py", line 89, in add_callback
    return super().add_callback(
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/pv.py", line 823, in add_callback
    self.get_ctrlvars()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/pv.py", line 46, in wrapped
    return func(self, *args, **kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/pv.py", line 739, in get_ctrlvars
    kwds = ca.get_ctrlvars(self.chid, timeout=timeout, warn=warn)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 634, in wrapper
    return fcn(*args, **kwds)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 1772, in get_ctrlvars
    metadata = get_with_metadata(chid, ftype=ftype, count=1, timeout=timeout,
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 634, in wrapper
    return fcn(*args, **kwds)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 1389, in get_with_metadata
    return get_complete_with_metadata(chid, count=count, ftype=ftype,
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 634, in wrapper
    return fcn(*args, **kwds)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 1521, in get_complete_with_metadata
    warnings.warn(msg % (name(chid), timeout))
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 575, in wrapper
    raise ChannelAccessException('Unexpected channel ID')
epics.ca.ChannelAccessException: Unexpected channel ID

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_dispatch.py", line 57, in run
    self.logger.exception(
Message: 'Exception occurred during callback %r (pvname=%r)'
Arguments: (<bound method EpicsSignalBase._pv_connected of EpicsSignalRO(read_pv='BL04I-MO-MAPT-01:Z.LLS', name='device_aperture_z_low_limit_switch', parent='device_aperture_z', timestamp=1707921483.5643125, auto_monitor=True, string=False)>, 'BL04I-MO-MAPT-01:Z.LLS')
--- Logging error ---
Traceback (most recent call last):
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_dispatch.py", line 55, in run
    callback(*args, **kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_pyepics_shim.py", line 145, in get_metadata_thread
    md = self.get_all_metadata_blocking(timeout=timeout)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_pyepics_shim.py", line 138, in get_all_metadata_blocking
    self.get_ctrlvars(timeout=timeout)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/pv.py", line 46, in wrapped
    return func(self, *args, **kwargs)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/pv.py", line 739, in get_ctrlvars
    kwds = ca.get_ctrlvars(self.chid, timeout=timeout, warn=warn)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 634, in wrapper
    return fcn(*args, **kwds)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 1772, in get_ctrlvars
    metadata = get_with_metadata(chid, ftype=ftype, count=1, timeout=timeout,
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 634, in wrapper
    return fcn(*args, **kwds)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 1389, in get_with_metadata
    return get_complete_with_metadata(chid, count=count, ftype=ftype,
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 634, in wrapper
    return fcn(*args, **kwds)
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 1521, in get_complete_with_metadata
    warnings.warn(msg % (name(chid), timeout))
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/epics/ca.py", line 575, in wrapper
    raise ChannelAccessException('Unexpected channel ID')
epics.ca.ChannelAccessException: Unexpected channel ID

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/scratch/ziq44869/development/hyperion/hyperion/.venv/lib/python3.10/site-packages/ophyd/_dispatch.py", line 57, in run
    self.logger.exception(
Message: 'Exception occurred during callback %r (pvname=%r)'
Arguments: (<function PyepicsShimPV.get_all_metadata_callback.<locals>.get_metadata_thread at 0x7fe1f8509900>, 'BL04I-MO-MAPT-01:Z.LLS')

```

**Comment by dperl-dls** [comment]
for some eiger statuses `pytest --random-order-seed=739099 -m "not s03"`
